### ISSUE TITLE
WARNING: Invalid :version specifier 0.1 for component "replic" from file #P"/Users/art/quicklisp/local-projects/replic/replic.asd", Substituting a string

### ISSUE THREAD

**Issue by svetlyak40wt** [vindarel/replic#2]
When I runned `qlot install` in a replic dir, it issued a warning from ASDF:

```
WARNING: Invalid :version specifier 0.1 for component "replic" from file #P"/Users/art/quicklisp/local-projects/replic/replic.asd", Substituting a string
```

ASDF expects a string as a version number on line: https://github.com/vindarel/replic/blob/master/replic.asd#L8

**Comment by svetlyak40wt** [comment]
Probably all asd files should be slightly changed according to [ASDF best practices](https://gitlab.common-lisp.net/asdf/asdf/blob/master/doc/best_practices.md).

**Comment by vindarel** [comment]
Thanks for the warning, I don't have it. 

\+1 for the best practices. Don't hesitate to point the bad practices you saw.
