### ISSUE TITLE
Any way to catch any input, not just commands?

### ISSUE THREAD

**Issue by jnc-nj** [vindarel/replic#6]
As part of my application, I would like to just catch user input and parse it without having to define a command for every viable input.

Is there any way to do this?

e.g. <user types "this is a string"> --> I get either '("this" "is" "a" "string") or just "this is a string"

**Comment by vindarel** [comment]
Maybe you just want readline ? See https://github.com/vindarel/cl-readline-example

see also how we use readline: https://github.com/vindarel/replic/blob/master/src/replic.lisp#L282

**Comment by jnc-nj** [comment]
> Maybe you just want readline ? See https://github.com/vindarel/cl-readline-example
> 
> see also how we use readline: https://github.com/vindarel/replic/blob/master/src/replic.lisp#L282

Thanks! I'll just fork the library and build ontop of (repl) I guess.

https://mrkkrp.github.io/cl-readline/ <-- this link isn't working for me btw (in China, sometimes io pages get blocked)

**Comment by jnc-nj** [comment]
> Maybe you just want readline ? See https://github.com/vindarel/cl-readline-example
> 
> see also how we use readline: https://github.com/vindarel/replic/blob/master/src/replic.lisp#L282

Another question, if you would be so kind as to answer -- for functions with multiple arguments, is there a way to define custom completion for each argument? The examples given and the code seems to indicate that each argument of the exported function can only complete from a single list.

**Comment by vindarel** [comment]
thanks, I fixed the link, it is now https://vindarel.github.io/cl-readline/

> for functions with multiple arguments, is there a way to define custom completion for each argument?

Good catch, you are right :) There is no way at the moment, but I do want it too. I created an issue: #7

**Comment by jnc-nj** [comment]
> thanks, I fixed the link, it is now https://vindarel.github.io/cl-readline/
> 
> > for functions with multiple arguments, is there a way to define custom completion for each argument?
> 
> Good catch, you are right :) There is no way at the moment, but I do want it too. I created an issue: #7

Oh one more thing (sorry for all the questions), is there a way to apply cl-ansi-color to documentation returned by `help`? Furthermore, is there a way to color function return values?

**Comment by vindarel** [comment]
It is definitely possible. What's cl-ansi-color though ? (couldn't find it) Do you mean cl-ansi-text ? [cl-ansi-term](https://github.com/vindarel/cl-ansi-term/) ? markdown output ?

> is there a way to color function return values?

not yet. Will have a look at it. (#8)

> sorry for all the questions

Glad to hear from users :)

**Comment by vindarel** [comment]
I suppose your use case is a situation where you re-use existing functions, and you cannot/don't want to create proper commands that would wrap them and do whatever you like ?

**Comment by jnc-nj** [comment]
> I suppose your use case is a situation where you re-use existing functions, and you cannot/don't want to create proper commands that would wrap them and do whatever you like ?

One new thing my users are requesting:
Right now when I build an application with roswell on macos my defined commands require quotes to execute (e.g. user has to type `test-command "foo" "bar"`); is this supposed to happen? If so, is there any way to not require the quote marks?

Edit: this only happens on macos.

**Comment by vindarel** [comment]
Looks like you are referencing to this, which was done in june: https://github.com/vindarel/replic/issues/4

We can type for instance

    lyrics "artist name" "song name"

(ps: If it isn't and if there is something macOs specific, please open a new issue)

**Comment by jnc-nj** [comment]
> Looks like you are referencing to this, which was done in june: #4
> 
> We can type for instance
> 
> ```
> lyrics "artist name" "song name"
> ```
> 
> (ps: If it isn't and if there is something macOs specific, please open a new issue)

Yes this is a new issue, please see #9

**Comment by vindarel** [comment]
Hi, you asked:

> for functions with multiple arguments, is there a way to define custom completion for each argument? The examples given and the code seems to indicate that each argument of the exported function can only complete from a single list.

it is done and documented. It is actually long done, but I didn't push to master without the doc…

---

with this

```
(defun say (verb name)
  (format t "~a, ~a !~&" verb name))
```

we can have different completions for each argument:

```
(replic.completion:add-completion "say"
                                  (list "greetings" "\"nice to see you\"")
                                  (lambda () *names*))
```

note also the quoted sentence.
